name: Kali-Linux-RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup RDP & Kali
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies xrdp wget curl
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        echo "kali:kali" | sudo chpasswd
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        chmod +x ngrok
        ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        ./ngrok tcp 3389 &
        sleep 10
        curl -s http://localhost:4040/api/tunnels | grep -o 'tcp://[0-9a-zA-Z.:]*'
